//
// Created by Olcay Taner YILDIZ on 9.11.2023.
//

#ifndef DEPENDENCYPARSER_TURKISHDEPENDENCYTYPE_H
#define DEPENDENCYPARSER_TURKISHDEPENDENCYTYPE_H

enum turkish_dependency_type{
    VOCATIVE, SUBJECT, DATIVE_ADJUNCT, OBJECT, POSSESSOR,
    MODIFIER, S_MODIFIER, ABLATIVE_ADJUNCT, DETERMINER_T, SENTENCE,
    CLASSIFIER, LOCATIVE_ADJUNCT, COORDINATION, QUESTION_PARTICLE, INTENSIFIER,
    INSTRUMENTAL_ADJUNCT, RELATIVIZER, NEGATIVE_PARTICLE, ETOL, COLLOCATION,
    FOCUS_PARTICLE, EQU_ADJUNCT, APPOSITION
};

typedef enum turkish_dependency_type Turkish_dependency_type;

#endif //DEPENDENCYPARSER_TURKISHDEPENDENCYTYPE_H
