//
// Created by Olcay Taner YILDIZ on 9.11.2023.
//

#ifndef DEPENDENCYPARSER_UNIVERSALDEPENDENCYTYPE_H
#define DEPENDENCYPARSER_UNIVERSALDEPENDENCYTYPE_H

enum universal_dependency_type{
    ACL, ADVCL, ADVMOD, AMOD, APPOS,
    AUX, CASE, CC, CCOMP, CLF,
    COMPOUND, CONJ, COP, CSUBJ, DEP,
    DET, DISCOURSE, DISLOCATED, EXPL, FIXED,
    FLAT, GOESWITH, IOBJ, LIST, MARK,
    NMOD, NSUBJ, NUMMOD, OBJ, OBL,
    ORPHAN, PARATAXIS, PUNCT, REPARANDUM, ROOT,
    VOCATIVE, XCOMP, ACL_RELCL, AUX_PASS, CC_PRECONJ,
    COMPOUND_PRT, DET_PREDET, FLAT_FOREIGN, NSUBJ_PASS, CSUBJ_PASS,
    NMOD_NPMOD, NMOD_POSS, NMOD_TMOD, ADVMOD_EMPH, AUX_Q,
    COMPOUND_LVC, COMPOUND_REDUP, CSUBJ_COP, NMOD_COMP, NMOD_PART,
    NSUBJ_COP, OBL_AGENT, OBL_TMOD, OBL_NPMOD, NSUBJ_OUTER,
    CSUBJ_OUTER, ADVCL_RELCL
};

typedef enum universal_dependency_type Universal_dependency_type;

#endif //DEPENDENCYPARSER_UNIVERSALDEPENDENCYTYPE_H
