//
// Created by Olcay Taner YILDIZ on 9.11.2023.
//

#ifndef DEPENDENCYPARSER_STANFORDDEPENDENCYTYPE_H
#define DEPENDENCYPARSER_STANFORDDEPENDENCYTYPE_H

enum stanford_dependency_type{
    ACOMP, ADVCL, ADVMOD, AGENT, AMOD, APPOS, AUX, AUXPASS, CC, CCOMP, CONJ, COP, CSUBJ, CSUBJPASS, DEP, DET,
    DISCOURSE, DOBJ, EXPL, GOESWITH, IOBJ, MARK, MWE, NEG, NN, NPADVMOD, NSUBJ, NSUBJPASS, NUM, NUMBER, PARATAXIS, PCOMP,
    POBJ, POSS, POSSESSIVE, PRECONJ, PREDET, PREP, PREPC, PRT, PUNCT, QUANTMOD, RCMOD, REF, ROOT, TMOD, VMOD, XCOMP, XSUBJ
};

typedef enum stanford_dependency_type Stanford_dependency_type;

#endif //DEPENDENCYPARSER_STANFORDDEPENDENCYTYPE_H
